# SPDX-License-Identifier: CC0-1.0
# DOSovoi reads this small key = value format. Unknown keys are errors.
enabled = true
mascot = bunny
render = ascii
color = false
motion = false
default_mode = serenity
care_plain_text = false
care_disable_color = true

